// Starter kitchen used by the demo login and as the classic app's in-memory fallback.
// Real restaurants load their own rows from moe_data.

export const DEFAULT_INVENTORY = [
  { section: "🌾  DRY GOODS", items: [
    { id: 5,  name: "Flour",                          order_unit: "Unit",    upu: 1,   vendor: "Anacapri", max_stock: 17,   reorder: 4   },
    { id: 6,  name: "Yeast",                          order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
  ]},
  { section: "🥦  PRODUCE", items: [
    { id: 8,  name: "Basil - Fresh",                  order_unit: "Each",    upu: 1,   vendor: "Anacapri", max_stock: 4,    reorder: 1   },
    { id: 9,  name: "Broccoli Crowns",                order_unit: "Case",    upu: 1,   vendor: "Anacapri", max_stock: 2,    reorder: 1   },
    { id: 10, name: "Cherry Tomatoes",                order_unit: "Unit",    upu: 1,   vendor: "Market",   max_stock: 4,    reorder: 1   },
    { id: 11, name: "Eggplant",                       order_unit: "Each",    upu: 1,   vendor: "Anacapri", max_stock: 2,    reorder: 1   },
    { id: 12, name: "Garlic - Peeled",                order_unit: "Each",    upu: 1,   vendor: "Anacapri", max_stock: 2,    reorder: 1   },
    { id: 13, name: "Jalapenos",                      order_unit: "Lbs",     upu: 1,   vendor: "Market",   max_stock: 4,    reorder: 1   },
    { id: 14, name: "Lemons",                         order_unit: "Case",    upu: 1,   vendor: "Anacapri", max_stock: 2,    reorder: 1   },
    { id: 15, name: "Mushrooms",                      order_unit: "Case",    upu: 1,   vendor: "Anacapri", max_stock: 4,    reorder: 1   },
    { id: 16, name: "Onions - Red",                   order_unit: "Bag",     upu: 1,   vendor: "Anacapri", max_stock: 2,    reorder: 1   },
    { id: 17, name: "Onions - Yellow",                order_unit: "Bag",     upu: 1,   vendor: "Anacapri", max_stock: 2,    reorder: 1   },
    { id: 18, name: "Parsley - Fresh",                order_unit: "Unit",    upu: 1,   vendor: "Market",   max_stock: 4,    reorder: 1   },
    { id: 19, name: "Potatoes",                       order_unit: "Case",    upu: 1,   vendor: "Anacapri", max_stock: 2,    reorder: 1   },
    { id: 20, name: "Romaine Lettuce",                order_unit: "Case",    upu: 1,   vendor: "Anacapri", max_stock: 2,    reorder: 1   },
    { id: 21, name: "Red Peppers",                    order_unit: "Case",    upu: 1,   vendor: "Anacapri", max_stock: 2,    reorder: 1   },
    { id: 22, name: "Green Peppers",                  order_unit: "Case",    upu: 1,   vendor: "Anacapri", max_stock: 2,    reorder: 1   },
    { id: 23, name: "Carrots",                        order_unit: "Bag",     upu: 1,   vendor: "Anacapri", max_stock: 2,    reorder: 1   },
    { id: 24, name: "Tomatoes",                       order_unit: "Case",    upu: 1,   vendor: "Anacapri", max_stock: 2,    reorder: 1   },
  ]},
  { section: "🧀  DAIRY", items: [
    { id: 26, name: "American Cheese",                order_unit: "Unit",    upu: 1,   vendor: "Anacapri", max_stock: 2,    reorder: 1   },
    { id: 27, name: "Butter Blocks",                  order_unit: "Case",    upu: 36,  vendor: "Anacapri", max_stock: 36,   reorder: 6   },
    { id: 28, name: "Butter Cups",                    order_unit: "Case",    upu: 100, vendor: "Anacapri", max_stock: 200,  reorder: 50  },
    { id: 29, name: "Eggs 15 Doz",                    order_unit: "Case",    upu: 2,   vendor: "Anacapri", max_stock: 4,    reorder: 1   },
    { id: 30, name: "Heavy Cream",                    order_unit: "Case",    upu: 12,  vendor: "Anacapri", max_stock: 12,   reorder: 4   },
    { id: 31, name: "Mozzarella - Curd",              order_unit: "Unit",    upu: 1,   vendor: "Anacapri", max_stock: 5,    reorder: 2   },
    { id: 32, name: "Mozzarella Grande",              order_unit: "Case",    upu: 2,   vendor: "Anacapri", max_stock: 10,   reorder: 3   },
    { id: 33, name: "Mozzarella Polly-O",             order_unit: "Case",    upu: 2,   vendor: "Anacapri", max_stock: 4,    reorder: 1   },
    { id: 34, name: "Pecorino Romano - Wheel",        order_unit: "Case",    upu: 1,   vendor: "Anacapri", max_stock: 4,    reorder: 1   },
    { id: 35, name: "Ricotta Cheese Grande",          order_unit: "Case",    upu: 4,   vendor: "Anacapri", max_stock: 8,    reorder: 2   },
    { id: 36, name: "Velveeta Cheese",                order_unit: "Unit",    upu: 1,   vendor: "Anacapri", max_stock: 2,    reorder: 1   },
    { id: 37, name: "Whole Milk",                     order_unit: "Case",    upu: 4,   vendor: "Anacapri", max_stock: 8,    reorder: 2   },
  ]},
  { section: "🥩  FRESH MEAT", items: [
    { id: 39, name: "Chicken Breast - Chicks Choice", order_unit: "Case",    upu: 1,   vendor: "Anacapri", max_stock: 10,   reorder: 3   },
    { id: 40, name: "Chicken Wings - Party",          order_unit: "Case",    upu: 1,   vendor: "Anacapri", max_stock: 4,    reorder: 1   },
    { id: 41, name: "Ham",                            order_unit: "Case",    upu: 1,   vendor: "Anacapri", max_stock: 2,    reorder: 1   },
  ]},
  { section: "🫙  OILS & CANNED GOODS", items: [
    { id: 43, name: "Liquid Clear Shortening",        order_unit: "Unit",    upu: 1,   vendor: "",         max_stock: 3,    reorder: 1   },
    { id: 44, name: "Soybean Oil",                    order_unit: "Unit",    upu: 1,   vendor: "",         max_stock: 3,    reorder: 1   },
    { id: 45, name: "711 (Tomato Sauce)",             order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 24,   reorder: 6   },
    { id: 46, name: "Saporito",                       order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 24,   reorder: 6   },
    { id: 47, name: "Valoroso",                       order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 24,   reorder: 6   },
    { id: 48, name: "Pineapple",                      order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 6,    reorder: 2   },
    { id: 49, name: "Black Sliced Olives",            order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 6,    reorder: 2   },
    { id: 50, name: "San Marzano Tomatoes",           order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
  ]},
  { section: "🍝  PASTA & RICE", items: [
    { id: 52, name: "Penne",                          order_unit: "Case",    upu: 20,  vendor: "",         max_stock: 40,   reorder: 10  },
    { id: 53, name: "Spaghetti",                      order_unit: "Case",    upu: 20,  vendor: "",         max_stock: 20,   reorder: 5   },
    { id: 54, name: "Linguine",                       order_unit: "Case",    upu: 20,  vendor: "",         max_stock: 20,   reorder: 5   },
    { id: 55, name: "Fettuccine",                     order_unit: "Case",    upu: 20,  vendor: "",         max_stock: 20,   reorder: 5   },
    { id: 56, name: "Capellini",                      order_unit: "Case",    upu: 20,  vendor: "",         max_stock: 20,   reorder: 5   },
    { id: 57, name: "Rigatoni",                       order_unit: "Case",    upu: 20,  vendor: "",         max_stock: 20,   reorder: 5   },
    { id: 58, name: "Whole Wheat Pasta",              order_unit: "Case",    upu: 20,  vendor: "",         max_stock: 20,   reorder: 5   },
    { id: 59, name: "Jumbo Shells",                   order_unit: "Case",    upu: 20,  vendor: "",         max_stock: 20,   reorder: 5   },
    { id: 60, name: "Lasagna",                        order_unit: "Case",    upu: 20,  vendor: "",         max_stock: 20,   reorder: 5   },
    { id: 61, name: "Carolina Rice Extra Long Grain", order_unit: "Bag",     upu: 1,   vendor: "",         max_stock: 4,    reorder: 1   },
  ]},
  { section: "❄️  FREEZER 1", items: [
    { id: 63, name: "Chicken Nuggets",                order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 64, name: "Chicken Tenders",                order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 65, name: "Boneless Wings",                 order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 66, name: "French Fries",                   order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 67, name: "Sweet Potato Fries",             order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 68, name: "Burgers",                        order_unit: "Case",    upu: 20,  vendor: "",         max_stock: 60,   reorder: 20  },
    { id: 69, name: "Wraps",                          order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 70, name: "Zucchini Sticks",                order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 71, name: "Cheese Ravioli",                 order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 72, name: "Mozzarella Sticks",              order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
  ]},
  { section: "❄️  FREEZER 2", items: [
    { id: 74, name: "Chopped Spinach",                order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 75, name: "Bacon Bits",                     order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 76, name: "Turkey",                         order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 4,    reorder: 1   },
    { id: 77, name: "Pepperoni",                      order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 78, name: "Ribeye Steak",                   order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 79, name: "Veal",                           order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 6,    reorder: 2   },
    { id: 80, name: "Chopped Meat",                   order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 6,    reorder: 2   },
    { id: 81, name: "Sausage",                        order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 4,    reorder: 1   },
    { id: 82, name: "Calamari",                       order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 83, name: "Peeled Shrimp",                  order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 84, name: "Baby Clams",                     order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 85, name: "Mussels",                        order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 86, name: "Tilapia",                        order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
  ]},
  { section: "🗃️  RACK 1", items: [
    { id: 88, name: "Salt",                           order_unit: "Bag",     upu: 1,   vendor: "",         max_stock: 4,    reorder: 1   },
    { id: 89, name: "Sugar",                          order_unit: "Bag",     upu: 1,   vendor: "",         max_stock: 4,    reorder: 1   },
    { id: 90, name: "Bread Crumbs",                   order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 91, name: "Panko Bread Crumbs",             order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 92, name: "Napkins",                        order_unit: "Case",    upu: 500, vendor: "",         max_stock: 1000, reorder: 200 },
    { id: 93, name: "Paper Plates",                   order_unit: "Case",    upu: 500, vendor: "",         max_stock: 1000, reorder: 200 },
  ]},
  { section: "🗄️  SHELF 1", items: [
    { id: 95,  name: "Powdered Sugar",                order_unit: "Bag",     upu: 1,   vendor: "",         max_stock: 4,    reorder: 1   },
    { id: 96,  name: "Cannoli Shells",                order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 97,  name: "Tie Bags",                      order_unit: "Case",    upu: 100, vendor: "",         max_stock: 200,  reorder: 50  },
    { id: 98,  name: "Ziplock Bags Gallon",           order_unit: "Case",    upu: 50,  vendor: "",         max_stock: 100,  reorder: 25  },
    { id: 99,  name: "Straws",                        order_unit: "Case",    upu: 500, vendor: "",         max_stock: 1000, reorder: 200 },
    { id: 100, name: "Forks",                         order_unit: "Case",    upu: 500, vendor: "",         max_stock: 1000, reorder: 200 },
    { id: 101, name: "Knives",                        order_unit: "Case",    upu: 500, vendor: "",         max_stock: 1000, reorder: 200 },
    { id: 102, name: "Spoons",                        order_unit: "Case",    upu: 500, vendor: "",         max_stock: 1000, reorder: 200 },
    { id: 103, name: "Pizza Stack",                   order_unit: "Case",    upu: 50,  vendor: "",         max_stock: 100,  reorder: 25  },
    { id: 104, name: "Gloves L",                      order_unit: "Case",    upu: 100, vendor: "",         max_stock: 200,  reorder: 50  },
    { id: 105, name: "Gloves XL",                     order_unit: "Case",    upu: 100, vendor: "",         max_stock: 200,  reorder: 50  },
    { id: 106, name: "18in Clear Film",               order_unit: "Roll",    upu: 1,   vendor: "",         max_stock: 4,    reorder: 1   },
    { id: 107, name: "24in Clear Film",               order_unit: "Roll",    upu: 1,   vendor: "",         max_stock: 4,    reorder: 1   },
    { id: 108, name: "12in Aluminum Foil",            order_unit: "Roll",    upu: 1,   vendor: "",         max_stock: 4,    reorder: 1   },
    { id: 109, name: "Plastic Bags",                  order_unit: "Case",    upu: 100, vendor: "",         max_stock: 200,  reorder: 50  },
    { id: 110, name: "Junior Wax",                    order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 111, name: "16oz Deli Container",           order_unit: "Case",    upu: 100, vendor: "",         max_stock: 200,  reorder: 50  },
    { id: 112, name: "5¾x6x3 Container",             order_unit: "Case",    upu: 100, vendor: "",         max_stock: 200,  reorder: 50  },
    { id: 113, name: "5¼x5⅜x2⅝ Container",          order_unit: "Case",    upu: 100, vendor: "",         max_stock: 200,  reorder: 50  },
  ]},
  { section: "🗄️  SHELF 2", items: [
    { id: 115, name: "8in Dome Lids",                 order_unit: "Case",    upu: 100, vendor: "",         max_stock: 200,  reorder: 50  },
    { id: 116, name: "8in Aluminum Dish",             order_unit: "Case",    upu: 100, vendor: "",         max_stock: 200,  reorder: 50  },
    { id: 117, name: "7in Dome Lids",                 order_unit: "Case",    upu: 100, vendor: "",         max_stock: 200,  reorder: 50  },
    { id: 118, name: "7in Aluminum Dish",             order_unit: "Case",    upu: 100, vendor: "",         max_stock: 200,  reorder: 50  },
    { id: 119, name: "20Lb Brown Bags",               order_unit: "Case",    upu: 500, vendor: "",         max_stock: 1000, reorder: 200 },
    { id: 120, name: "12Lb Brown Bags",               order_unit: "Case",    upu: 500, vendor: "",         max_stock: 1000, reorder: 200 },
    { id: 121, name: "Hero Containers",               order_unit: "Case",    upu: 200, vendor: "",         max_stock: 400,  reorder: 100 },
    { id: 122, name: "4oz Souffle Lids",              order_unit: "Case",    upu: 200, vendor: "",         max_stock: 400,  reorder: 100 },
    { id: 123, name: "4oz Souffle Cups",              order_unit: "Case",    upu: 200, vendor: "",         max_stock: 400,  reorder: 100 },
    { id: 124, name: "2oz Souffle Lids",              order_unit: "Case",    upu: 200, vendor: "",         max_stock: 400,  reorder: 100 },
    { id: 125, name: "2oz Souffle Cups",              order_unit: "Case",    upu: 200, vendor: "",         max_stock: 400,  reorder: 100 },
    { id: 126, name: "Heinz Ketchup",                 order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 127, name: "Mayo",                          order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 128, name: "Honey Mustard Dressing",        order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 129, name: "Blue Cheese Dressing",          order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 6,    reorder: 2   },
    { id: 130, name: "Ranch Dressing",                order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 131, name: "Vinegar",                       order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 132, name: "Italian Dressing",              order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 133, name: "Balsamic Dressing",             order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 134, name: "Olive Oil",                     order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 6,    reorder: 2   },
    { id: 135, name: "White Wine",                    order_unit: "Case",    upu: 12,  vendor: "",         max_stock: 12,   reorder: 4   },
    { id: 136, name: "Vodka",                         order_unit: "Case",    upu: 12,  vendor: "",         max_stock: 12,   reorder: 4   },
    { id: 137, name: "Marsala Wine",                  order_unit: "Case",    upu: 12,  vendor: "",         max_stock: 12,   reorder: 4   },
  ]},
  { section: "🥫  CONDIMENTS & SAUCES", items: [
    { id: 139, name: "Mango",                         order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 140, name: "Garlic Parm",                   order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 141, name: "Franks Red Hot",                order_unit: "Gallon",  upu: 1,   vendor: "",         max_stock: 4,    reorder: 1   },
    { id: 142, name: "BBQ Sauce",                     order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 143, name: "Honey BBQ Sauce",               order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 144, name: "Taco Sauce",                    order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 145, name: "Tarter Sauce",                  order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 146, name: "Lemon Juice",                   order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
  ]},
  { section: "📦  BOXES", items: [
    { id: 148, name: "18in Boxes",                    order_unit: "Bundle",  upu: 50,  vendor: "",         max_stock: 100,  reorder: 25  },
    { id: 149, name: "16in Boxes",                    order_unit: "Bundle",  upu: 50,  vendor: "",         max_stock: 100,  reorder: 25  },
    { id: 150, name: "14in Boxes",                    order_unit: "Bundle",  upu: 50,  vendor: "",         max_stock: 100,  reorder: 25  },
    { id: 151, name: "12in Boxes",                    order_unit: "Bundle",  upu: 50,  vendor: "",         max_stock: 100,  reorder: 25  },
    { id: 152, name: "10in Boxes",                    order_unit: "Bundle",  upu: 50,  vendor: "",         max_stock: 100,  reorder: 25  },
    { id: 153, name: "Tommys Paper Cups",             order_unit: "Case",    upu: 50,  vendor: "",         max_stock: 100,  reorder: 25  },
  ]},
  { section: "🛍️  DISPOSABLES & PACKAGING", items: [
    { id: 155, name: "Full Size Medium Trays",        order_unit: "Case",    upu: 50,  vendor: "",         max_stock: 100,  reorder: 25  },
    { id: 156, name: "Half Size Medium Trays",        order_unit: "Case",    upu: 50,  vendor: "",         max_stock: 100,  reorder: 25  },
    { id: 157, name: "Full Size Deep Trays",          order_unit: "Case",    upu: 50,  vendor: "",         max_stock: 100,  reorder: 25  },
    { id: 158, name: "Half Size Deep Trays",          order_unit: "Case",    upu: 50,  vendor: "",         max_stock: 50,   reorder: 15  },
    { id: 159, name: "Full Size Lids",                order_unit: "Case",    upu: 50,  vendor: "",         max_stock: 100,  reorder: 25  },
    { id: 160, name: "Half Size Lids",                order_unit: "Case",    upu: 50,  vendor: "",         max_stock: 100,  reorder: 25  },
    { id: 161, name: "Masking Tape Roll",             order_unit: "Each",    upu: 1,   vendor: "",         max_stock: 4,    reorder: 1   },
    { id: 162, name: "Clear Bags",                    order_unit: "Case",    upu: 100, vendor: "",         max_stock: 200,  reorder: 50  },
    { id: 163, name: "Black Bags",                    order_unit: "Case",    upu: 100, vendor: "",         max_stock: 200,  reorder: 50  },
  ]},
  { section: "🧹  CLEANING SUPPLIES", items: [
    { id: 166, name: "Bleach",                        order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 167, name: "Pine Cleaner",                  order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 168, name: "Oven Cleaner",                  order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 169, name: "Glass Cleaner",                 order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 170, name: "Joy Dish Soap",                 order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 171, name: "Steel Sponge",                  order_unit: "Case",    upu: 12,  vendor: "",         max_stock: 24,   reorder: 6   },
    { id: 172, name: "Broom Head",                    order_unit: "Each",    upu: 1,   vendor: "",         max_stock: 4,    reorder: 1   },
    { id: 173, name: "Mop Head",                      order_unit: "Each",    upu: 1,   vendor: "",         max_stock: 4,    reorder: 1   },
    { id: 174, name: "Toilet Bowl Gel",               order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 175, name: "Bathroom Bleach Foamer Spray",  order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 176, name: "Scrubbing Bubbles",             order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 177, name: "Lysol Spray",                   order_unit: "Case",    upu: 6,   vendor: "",         max_stock: 12,   reorder: 3   },
    { id: 178, name: "Brillo Pads",                   order_unit: "Case",    upu: 12,  vendor: "",         max_stock: 24,   reorder: 6   },
  ]},
  { section: "❄️  BOX ROOM FREEZER", items: [
    { id: 180, name: "Cheesecake",                    order_unit: "Each",    upu: 1,   vendor: "",         max_stock: 4,    reorder: 1   },
    { id: 181, name: "Tres Leche",                    order_unit: "Each",    upu: 1,   vendor: "",         max_stock: 4,    reorder: 1   },
    { id: 182, name: "Chocolate Moose",               order_unit: "Each",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
    { id: 183, name: "Red Velvet",                    order_unit: "Each",    upu: 1,   vendor: "",         max_stock: 4,    reorder: 1   },
    { id: 184, name: "Cannoli Cream",                 order_unit: "Each",    upu: 1,   vendor: "",         max_stock: 4,    reorder: 1   },
    { id: 185, name: "Tiramisu",                      order_unit: "Case",    upu: 1,   vendor: "",         max_stock: 2,    reorder: 1   },
  ]},
];

export const DEMO_USERS = {
  "owner@kitchen.com":    { password: "owner123",    role: "owner",    name: "Owner",    group: "demo" },
  "employee@kitchen.com": { password: "employee123", role: "employee", name: "Employee", group: "demo" },
  "rep@anacapri.com":     { password: "rep123",       role: "rep",      name: "Enzo Marino", repCode: "DEMO", repCompany: "Anacapri" },
};

// ─── DEFAULT VENDORS (Tommy's starter) ───────────────────────────────────────
export const DEFAULT_VENDORS = [
  { id: 1, name: "Anacapri", orderDays: [3] },   // Wednesday
  { id: 2, name: "Market",   orderDays: [4] },   // Thursday
];

